version: '3.5'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

services:
  ngrok:
    build: .
    image: 0raymond0/ngrok-space:latest
    logging: *default-logging
    ports:
      - "${PORT:-8888}:8888"


